### ISSUE TITLE
Cannot build app

### ISSUE THREAD

**Issue by ahsanahmed321** [pixijs/examples#113]
when using npm run build it is showing this

F:\pixi-test\examples\examples\js\plugin-picture\mask-blur.js
   9:22  error  Strings must use singlequote                                  quotes
  11:16  error  Strings must use singlequote                                  quotes
  11:37  error  Strings must use singlequote                                  quotes
  18:5   error  Expected exception block, space or tab after '//' in comment  spaced-comment
  43:23  error  There should be no line break before or after '='             operator-linebreak
  44:9   error  Strings must use singlequote                                  quotes
  44:47  error  '+' should be placed at the beginning of the line             operator-linebreak
  45:9   error  Strings must use singlequote                                  quotes
  45:59  error  '+' should be placed at the beginning of the line             operator-linebreak
  46:9   error  Strings must use singlequote                                  quotes
  59:30  error  Strings must use singlequote                                  quotes
  59:54  error  Missing trailing comma                                        comma-dangle

F:\pixi-test\examples\examples\js\text\text.js
  25:22  error  Missing trailing comma         comma-dangle
  40:22  error  Strings must use singlequote   quotes
  45:17  error  Strings must use singlequote   quotes
  46:15  error  Strings must use singlequote   quotes
  47:24  error  Missing trailing comma         comma-dangle
  51:23  error  A space is required after ','  comma-spacing

**Comment by ShukantPal** [comment]
These are linting errors. `npm run js` should work fine for now.

**Comment by ahsanahmed321** [comment]
Thanks buddy
