### ISSUE TITLE
graphics simple / drawStar is not a function

### ISSUE THREAD

**Issue by Karel-Kroeze** [pixijs/examples#116]
https://pixijs.io/examples/#/graphics/simple.js

![image](https://user-images.githubusercontent.com/6831612/112720489-f6e56c00-8efe-11eb-94ae-4f91d6543154.png)

I'm new to pixi.js, but I expect this function was deprecated/renamed at some point?

**Comment by bigtimebuddy** [comment]
Yup this got moved to graphic-extras. Should be an easy fix

**Comment by zetaraku** [comment]
The error still exists :(
![Screenshot 2023-02-10 122637](https://user-images.githubusercontent.com/9212875/218000608-d9c5d55b-794a-4db7-b079-226aa0f5f854.png)

**Comment by bigtimebuddy** [comment]
There was an issue with the main project building some of the optional packages. Looking into it.
