### ISSUE TITLE
v4 examples are not working

### ISSUE THREAD

**Issue by stbaer** [pixijs/examples#13]
This is the console error:

```
ERROR: 0:116: '26' : memory exhausted 

pixi.js:6453 WebGL: INVALID_VALUE: attachShader: no object or object deleted

pixi.js:6459 Pixi.js Error: Could not initialize shader.24.compileProgram @ pixi.js:6459
19.Shader @ pixi.js:5769
generateMultiTextureShader @ pixi.js:17743
88.SpriteRenderer.onContextChange @ pixi.js:17470
emit @ pixi.js:1238
...
window.onload   @   VM294:1
```

**Comment by GoodBoyDigital** [comment]
Hi @stbaer Thanks for all sharing this! Can I ask what device / os this error appeared on? Thanks!

**Comment by GoodBoyDigital** [comment]
ok, think i fixed it! let me know, cheers!

**Comment by stbaer** [comment]
Hi @GoodBoyDigital - Chrome 49 and FF 47 under Linux. Also getting this error on the pone (Android/Chrome).

**Comment by stbaer** [comment]
The error is still there, it has also been reported here https://github.com/pixijs/pixi.js/issues/2431#issuecomment-204673089 . It's a pixi.js issue and not an issue with the examples so feel free to close it here.

**Comment by GoodBoyDigital** [comment]
Cool, would you mind checking again with the latest version? I think I fixed it, but can't recreate here :/
Cheers!

**Comment by stbaer** [comment]
Nice, looking good with latest dev  :+1:
