### ISSUE TITLE
Can assets in this repo be used for commercial purposes?

### ISSUE THREAD

**Issue by rkreutz** [pixijs/examples#147]
Hey there, I was just wondering if the characters in this repo could be used commercially in other websites? I've noticed the package json file mentions MIT license, I'm just not sure if that applies to all the assets in the repo as well?

If they so happen to not be allowed to be used commercially, does anyone know a marketplace where I could by assets to use with this framework? (I'm specially interested in characters that could be used with the spine framework)

Thanks 😊

**Comment by ivanpopelyshev** [comment]
spine has its own license, you can ask esotericsoftware guys
