### ISSUE TITLE
How to debug examples in Chrome?

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [pixijs/examples#149]
I cloned examples repo `git clone https://github.com/pixijs/examples` and built it with `npm run build`. I want to be able to debug examples in Chrome. I mean set breakpoint in PIXI.Application, etc. With `http-server -c-1` I do not see such an option. Running build seemed to be bundled and minified (`pixi-examples.min.js`). Is there such an option to debug examples? Or maybe should I request it?

![image](https://user-images.githubusercontent.com/6131040/162403538-d8cf573b-7461-461b-8434-c6a9a10d50a4.png)

**Comment by bigtimebuddy** [comment]
There is a watch script in the package.json, did you try that?

**Comment by dmitrykolesnikovich** [comment]
Yes it works for me now, thank you. I thought first you should run http-server or npm run watch. And in fact you should run one after another. I now can debug stuff, thanks again.

**Comment by dmitrykolesnikovich** [comment]
Watch script helped. Is there some way for me to edit Pixi classes? For now I only able to debug it as is.

**Comment by dmitrykolesnikovich** [comment]
![Screen Shot 2022-04-08 at 13 45 52](https://user-images.githubusercontent.com/6131040/162420961-3921044f-5926-4966-badb-c1381f24bcc4.png)

**Comment by ivanpopelyshev** [comment]
if you have your own build of pixi, you can put it in `dist` folder and choose "local" in versions. If you put it without sourcemaps, you can just debug a long file.

In current setup there's no way to add breakpoints in the example itself, only in your local `pixi.js`. It didnt stop me from using it as one of my mail tools though :)

**Comment by bigtimebuddy** [comment]
The dropdown where you'd select the Pixi version, there is a local option. You can link your pixi.js to this local version and that should give you a debug environment where you can watch both the examples and Pixi.

**Comment by dmitrykolesnikovich** [comment]
I end up using IntelliJ IDEA Ultimate + pixi.js in `dist` folder. I debug Pixi as a big monolithic JS file, but the only problem now I can not debug examples itself. Maybe you guys know IntelliJ related stuff? BTW `watch` script does not help. There is a video of me [trying to debug PIXI examples with IntelliJ](https://www.youtube.com/watch?v=Gk9MbGseeTQ).

**Comment by bigtimebuddy** [comment]
Do we need to provide more documentation about this?

**Comment by dmitrykolesnikovich** [comment]
Honestly I tried three.js and all my favourite tooling works straightly out of the box. It's such a joy that I do not plan to spend more time with pixi.  All the best with your tech, thanks for replies anyway.
