### ISSUE TITLE
Upgrade to v7.0.0

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/examples#156]
This project will need some work upgrading to v7:

* Removes interaction plugin (replaces with events)
* Removes Loader (replaces with Assets)

There are several plugins that will also require updating.

**Comment by SuperSodaSea** [comment]
Seems that using plugins that don't provided as standalone files in v7 such as `@pixi/assets` and `@pixi/events` will show errors in console. Maybe we need to add some condition and don't load them for v7. (The examples can still work normally though, but these errors are annoying.)

![image](https://user-images.githubusercontent.com/8724868/196057971-e71519e2-7c49-49e0-a8d4-19c013278eae.png)
