### ISSUE TITLE
Features: Improvements to Examples

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/examples#164]
### Feature Improvements

Having upgrade examples to work with v7, there are bunch of improvements that could make this examples project much better.

* [ ] Convert src code to be React, remove jQuery
* [ ] Convert styles to be SASS instead of LESS
* [ ] Upgrade ESLint to latest, revisit config rules
* [ ] Use History API to track changes (back, forward navigation)
* [ ] Decouple the file system organization and manifest organization
* [ ] Handle 404s with requests
* [ ] Add embed code generation (e.g., `?embed=1&lite=1`)
* [ ] Don't embed plugin builds, source from an external CDN
* [ ] Support for export for 3rd party tools (e.g, codepen, jsfiddle, codesandbox.io)
* [ ] Revisit responsive design for large screen-sizes (weird positioning)

**Comment by vikpe** [comment]
Have you considered [VitePress](https://vitepress.vuejs.org/) or [Astro](https://astro.build/)? they are both really awesome.

[StackBlitz](https://stackblitz.com/) is great for [embedding](https://developer.stackblitz.com/guides/integration/embedding) code [from GitHub](https://developer.stackblitz.com/guides/user-guide/importing-projects#import-from-github).

**Comment by bigtimebuddy** [comment]
I think we have a bigger plan to create a new website for pixijs.com which will integrate these things. That project is happening right now and hopefully we will be able to sunset this project.

Thanks for the suggestions.
