### ISSUE TITLE
Video doesn't show in the examples

### ISSUE THREAD

**Issue by sv-hmelevsky** [pixijs/examples#18]
Hi guys, i found the trouble.
Maybe you know about that.
But anyway, in example on this **[LINK](https://pixijs.github.io/examples/?v=v4.0.0#/basics/video.js)**
Video show only in 4.0.0 version.
In version 4.0.1 and above video doesn't work, only music.
I checked in Google Chrome 53.0.2785.143 and Firefox 43.0.2

**Comment by rtpHarry** [comment]
I'm seeing this too but only on 4.0.1, 4.0.2, and 4.0.3.

It works on newer versions.

**Comment by englercj** [comment]
This was a bug in 4.0.x, which was fixed.
