### ISSUE TITLE
I found git examples of v7 and v5, but not v6?

### ISSUE THREAD

**Issue by ado5** [pixijs/examples#180]
Could not find examples of version 6 on the official website now, could you create examples-v6 please?

**Comment by ivanpopelyshev** [comment]
That's what I use for v6:

![image](https://github.com/pixijs/examples/assets/695831/948f63f9-6544-4c0f-bf2c-43d640a83841)

I recommend to clone repo , create v6 branch that looks on that commit and use it ) It salso much easier to debug than v7 due to lack of copy dir operation

**Comment by bigtimebuddy** [comment]
examples-v5 also covers v6

**Comment by ado5** [comment]
Thanks for your help!
