### ISSUE TITLE
Interactivity Error in Latest ver..

### ISSUE THREAD

**Issue by michael829** [pixijs/examples#19]
I found I can't do click event in this demo...
_addr:_
**http://pixijs.github.io/examples/?v=v4.1.0#/demos/interactivity.js**

In fact other demo like:
_addr:_
**http://pixijs.github.io/examples/?v=v4.1.0#/basics/click.js**

are works bad!!!! 

And I have test other version....I found this is only in latest ver..It works fine in v4.0.3

My Device info:
Mac OS 10.11.5 and Mac Chrome v53.0.2785.30 dev (64-bit)

**Comment by englercj** [comment]
This issue is currently open here: https://github.com/pixijs/pixi.js/issues/3167
