### ISSUE TITLE
Pixi Spine Walking Animation Example Throws Error

### ISSUE THREAD

**Issue by dalevfenton** [pixijs/examples#21]
The example shown on the documentation site here throws an error when I try to view it:
http://pixijs.github.io/examples/#/spine/spineboy.js

Error in console:
Uncaught Error: Cannot add resources while the loader is running.
    at Loader.add (pixi.js:5190)
    at Loader.<anonymous> (pixi-spine.js:5457)
    at pixi.js:5432
    at next (pixi.js:6616)
    at Loader.bitmapFontParser (pixi.js:32776)
    at pixi.js:5432
    at next (pixi.js:6616)
    at Loader.spritesheetParser (pixi.js:33098)
    at pixi.js:5432
    at next (pixi.js:6616)

![pixi-example-error](https://cloud.githubusercontent.com/assets/16996057/21722804/2d172d9e-d3fc-11e6-8ba3-2862b2b92405.PNG)

It looks like all the spine examples have this issue since none are working for me. 
On Chrome Version 55.0.2883.87 m

**Comment by bigtimebuddy** [comment]
@englercj probably requires an update to the v2 API of resource-loader?
