### ISSUE TITLE
Cannot set backgroundColor to black (0x000000)

### ISSUE THREAD

**Issue by tran2** [pixijs/examples#3]
When I set backgroundColor: 0x000000, it won't turn black unless it's inside quote '0x000000'. 

```
var renderer = PIXI.autoDetectRenderer(800, 800,  {backgroundColor: 0x000000});
```

**Comment by englercj** [comment]
This bug is better reported on the pixi repo, instead of the examples:

https://github.com/GoodBoyDigital/pixi.js/issues

In fact, I'm pretty sure this is fixed in the latest dev branch.
