### ISSUE TITLE
what editor they use to create the animation ?

### ISSUE THREAD

**Issue by mapuerta** [pixijs/examples#36]
Hi I am new using this framework.
I see this [example](http://scottmcdonnell.github.io/pixi-examples/index.html?s=spine&f=dragon.js&title=Dragon&plugins=pixi-spine&v=v4.0.1) and I would like to know which editor they use to generate the json with the animation. This is just a doubt. Your answer will very help

**Comment by ivanpopelyshev** [comment]
http://esotericsoftware.com/

https://github.com/pixijs/pixi-spine is spine runtime based on [spine-ts](https://github.com/EsotericSoftware/spine-runtimes/tree/3.6/spine-ts) optimized for pixi.

**Comment by mapuerta** [comment]
Thank!!

**Comment by ivanpopelyshev** [comment]
You can also try DragonBones (bugs), Spriter (no pixi runtime) or [Creature](http://creature.kestrelmoon.com/) ( That's a good one! ).

**Comment by mapuerta** [comment]
Do you know if there is a free tool?

**Comment by ivanpopelyshev** [comment]
[DragonBones](http://www.dragonbones.com/en/index.html). But I dont have any guarantees that it works. They have [pixi runtime](https://github.com/DragonBones/DragonBonesJS)

Also, there were a number of patches on pixi-spine, it can work if DragonBones exports in spine format. However, legally, you have to buy original Spine Editor to use pixi-spine runtime.

If you're good enough you can make Spriter plugin, people are requesting it, there's even 50$ bounty: https://github.com/pixijs/pixi-spine/issues/81

**Comment by ivanpopelyshev** [comment]
Also, look at pricing of [ToonBoom](https://www.toonboom.com/) , it costs much more than Spine.

**Comment by ivanpopelyshev** [comment]
Found dragonbones runtime, look up ^^^

**Comment by gothambrowny** [comment]
You can use Spine software for making Jason and atlas or install a spine to Jason plugin in adobe after effect  to export Jason file

**Comment by mapuerta** [comment]
Ok Thanks for your help... A last question. [pixi-flash](https://www.npmjs.com/package/pixi-flash) can work for the same purpose ?

**Comment by gothambrowny** [comment]
Yes it will work on pixi. Js

**Comment by ivanpopelyshev** [comment]
@gothambrowny 

Wtf is Jason? Can I get an info on it ? I want to confuse other devs too!

@mapuerta 

2 years ago, updated for pixi-v4. It should work with flash but you'll have to fix it of something goes wrong.

**Comment by gothambrowny** [comment]
Sorry wrong comment

**Comment by mapuerta** [comment]
@ivanpopelyshev @gothambrowny Thanks for your help
