### ISSUE TITLE
Update for pixi-spine

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/examples#4]
@englercj Can you tell me where pixi.js is referenced from html, so I can add pixi-spine there too?

**Comment by englercj** [comment]
Pixi is loaded dynamically because you can select the active version:

https://github.com/pixijs/examples/blob/master/_site/js/viewer.js#L18-L26

As far as how to load pixi-spine, it would be nice if we should in the `_details` file describe what plugins an example would need and then the code would load those plugins only for the examples that use them.

**Comment by ivanpopelyshev** [comment]
I have to add a file with plugins list for each version, right?

**Comment by englercj** [comment]
@ivanpopelyshev this is where it get complicated, basically the examples are only on v3+ so it should be fine to just say like `"plugins": ["pixi-spine"]` or something in a `_details` file.

But that functionality doesn't exist yet :D

**Comment by ivanpopelyshev** [comment]
So, where do I put that file? _site/js or just in root? Is that json or js?

**Comment by englercj** [comment]
Each example folder has a `_details.json` file that describes the examples in that folder. For example:

https://github.com/pixijs/examples/blob/master/examples/basics/_details.json

The [`generateManifest.js`](https://github.com/pixijs/examples/blob/master/generateManifest.js) script combines the files into the [example manifest](https://github.com/pixijs/examples/blob/master/_site/manifest.json). That manifest file is what is loaded at runtime to properly build the examples pages.

I'm suggesting adding a `plugins` key to an object describing an example that needs pixi-spine. Then implementing support for that key in the site code.

**Comment by ivanpopelyshev** [comment]
Ah, now I'm felling stupid :) thank you!
