### ISSUE TITLE
mesh examples not working

### ISSUE THREAD

**Issue by mtiziano** [pixijs/examples#42]
mesh examples are not working, black canvas

http://pixijs.io/examples/#/mesh/triangle-color.js

**Comment by ivanpopelyshev** [comment]
Look at first line of the example ;) Its for pixi-v5. You have to choose "next" branch.

**Comment by ivanpopelyshev** [comment]
new v5 release will be tomorrow or the day after, docs and typings will be included.

**Comment by mtiziano** [comment]
Thanks @ivanpopelyshev!! Seems I approached Pixi at the right time 😃

**Comment by jasonsturges** [comment]
Pixi.js website mesh examples remain confusing, having to press 'next' to advance to v5.

Otherwise, by default the website experience is:
```
VM514:6 Uncaught TypeError: PIXI.Geometry is not a constructor
    at window.onload (<anonymous>:6:16)
```

**Comment by themoonrat** [comment]
Mesh examples now only work in v5, and if you try to look at them in v4, a message will let you know why :)
