### ISSUE TITLE
Is it possible to create a transparent sprite?

### ISSUE THREAD

**Issue by tifDev** [pixijs/examples#49]
I need transparent sprites that will be placed on canvas to trigger specific events when clicked. This way they dont override the background image of the canvas.

**Comment by ivanpopelyshev** [comment]
`renderable=false` or `alpha=0` should work. Also, `hitArea` to specify local area that can be hit, it might be any shape.

**Comment by bigtimebuddy** [comment]
You can also use `hitArea` on an empty Sprite to define your hit region:
http://jsfiddle.net/5t4s8zfy/2/
