### ISSUE TITLE
Video example issues

### ISSUE THREAD

**Issue by JuCarr** [pixijs/examples#52]
1. testVideo.mp4 returns a 404 error
2. This feature seems broken on Firefox Android (I tested it with a video of mine). It says NS_ERROR_NOT_AVAILABLE

**Comment by bigtimebuddy** [comment]
This was just fixed in **dev** (latest release is broken): https://pixijs.io/examples/?v=dev#/basics/video.js

See: https://github.com/pixijs/pixi.js/pull/5170
