### ISSUE TITLE
Examples broken, PIXI not loading

### ISSUE THREAD

**Issue by christopher4lis** [pixijs/examples#66]
Looks like all examples on the website are broken at the minute:

![image](https://user-images.githubusercontent.com/7675752/56396684-04235780-620e-11e9-990e-da68c9ec1dd1.png)

**Comment by bigtimebuddy** [comment]
This is a known issue. We are having a problem with AWS. Hope to resolve ASAP.

**Comment by bigtimebuddy** [comment]
Fixed!

**Comment by manix** [comment]
This seems to have happened again.

**Comment by bigtimebuddy** [comment]
Thanks for pointing this out @manix.

@Zyie, I believe this maybe from the polyfill conversion (#6654). Would you mind taking a look?

```
requestAnimationFrame.ts:24 Uncaught ReferenceError: global is not defined
    at requestAnimationFrame.ts:24
    at index.js:19
```

**Comment by Zyie** [comment]
Can do

**Comment by bigtimebuddy** [comment]
I think part of the issue our tests didn't catch this is because we run in Electron which has a `global` object. I'm not sure why it was working before though. We could probably change that to `window`.

**Comment by manix** [comment]
Woah, that was quick!

**Comment by bigtimebuddy** [comment]
For example:
**master** (works)
```js
        if (!(commonjsGlobal$1.performance && commonjsGlobal$1.performance.now)) {
	    var startTime = Date.now();
	    if (!commonjsGlobal$1.performance) {
	        commonjsGlobal$1.performance = {};
	    }
	    commonjsGlobal$1.performance.now = function () { return Date.now() - startTime; };
	}
```
**dev** (broken)
```js
	if (!(global.performance && global.performance.now)) {
	    var startTime_1 = Date.now();
	    if (!global.performance) {
	        global.performance = {};
	    }
	    global.performance.now = function () { return Date.now() - startTime_1; };
	}
```

**Comment by Zyie** [comment]
@bigtimebuddy Ok so i figured it out. The commonjs rollup plugin cannot work with typescript, [issue](https://github.com/rollup/rollup-plugin-commonjs/issues/377)

If i convert the `requestAnimationFrame` file back to js `commonjsGlobal` appears again

**Comment by Zyie** [comment]
using `window` might be the easiest fix here
