### ISSUE TITLE
missing bezier arrow example

### ISSUE THREAD

**Issue by jonlepage** [pixijs/examples#75]
hi, i want draw a dynamic arrow with bezier curve, but i can find demo on how draw a arrow with graphics.
how i can perform this?
![image](https://user-images.githubusercontent.com/24865815/64905552-0d72fc00-d6a8-11e9-92f7-3bea282b174a.png)

it for use in this kind of context, but i can't perform this in photoshop, too complex to do.
![bezier with arrow](https://user-images.githubusercontent.com/24865815/64905536-d56bb900-d6a7-11e9-864a-bc08e411ea37.gif)
it possible to add a bezier arrow in pixi demo to help understand?
Or if someone have a code to share ?
https://www.pixiplayground.com/#/edit/cohufb~Y8gCB8VPlmql8f
thanks in advance.

**Comment by eXponenta** [comment]
It so easy!
Basic of geometrical math (for 12 years old schoolers in Russia)
https://www.pixiplayground.com/#/edit/pesHdzN6XgRXg4N3U1b4U

**Comment by jonlepage** [comment]
lol hum not really easy, but thank you lol you are awesome
